# Generated by Django 5.0.7 on 2024-08-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='staus',
            new_name='status',
        ),
    ]
