# Generated by Django 5.0.7 on 2024-08-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='time',
            new_name='contact_time',
        ),
    ]
