# Generated by Django 5.0.7 on 2024-08-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_community_contact_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='contact_time',
            new_name='start_time',
        ),
    ]
