# Generated by Django 5.0.7 on 2024-08-19 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_contact_time_community_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
