# Generated by Django 5.0.7 on 2024-08-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userappointments_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
