# Generated by Django 5.0.7 on 2024-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_appointments_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
