# Generated by Django 5.0.7 on 2024-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_appointments_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointments',
            name='status',
            field=models.CharField(default='wait for response', max_length=100),
        ),
    ]
